// Release feature guides. Commands here are instructional; this page never runs them.
const featureGuides = {
  ha97: {
    release:'MySQL 9.7 LTS', category:'Replication & HA', title:'See replication pressure before it becomes lag.',
    lead:'9.7 brings applier metrics, Group Replication flow-control statistics, resource management, and primary-election improvements into the Community release story. The practical goal is to distinguish receive, apply, and group backpressure.',
    changes:[['Applier metrics','Observe the replica apply stage separately from the receiver and relay-log backlog.'],['Group flow control','Use group statistics to understand when members are slowing writers.'],['Resource manager & election','Review group resource behavior and primary-election settings before a failover exercise.']],
    steps:[['Establish a baseline','Record source write rate, replica lag, applier status, and Group Replication member health under normal load.','SHOW REPLICA STATUS\\G\nSELECT * FROM performance_schema.replication_applier_status_by_worker;'],['Introduce controlled pressure','On a disposable topology, increase writes or slow a replica; observe whether receive, apply, or group flow control is the constraint.','SELECT * FROM performance_schema.replication_group_member_stats;'],['Compare recovery','Remove the pressure and record time to drain backlog. For Group Replication, test election only in a planned failover window.','SELECT * FROM performance_schema.replication_group_members;']],
    outcome:'A measurement-led HA decision: identify the bottleneck before changing worker counts or group settings.',
    caution:'Some component-specific metrics require installation and configuration; check the exact 9.7 component instructions before using them.',
    docs:'https://dev.mysql.com/doc/relnotes/mysql/9.7/en/news-9-7-0.html'
  },
  telemetry: {
    release:'MySQL 9.7 LTS', category:'Observability', title:'Connect database signals to your telemetry stack.',
    lead:'The MySQL Telemetry component moves into Community in 9.7. It provides the instrumentation interface for OpenTelemetry-style observability; exporters and signal coverage must be configured separately.',
    changes:[['One signal vocabulary','Relate server metrics, traces, and logs to application incidents.'],['Operational context','Correlate query behavior with replica and host signals.'],['Exporter choice','Use a supported provider or implement a component for the signals you need.']],
    steps:[['Inventory the environment','Confirm the 9.7 server build and which telemetry components or exporters are installed.','SELECT VERSION();\nSELECT * FROM mysql.component;'],['Define a small pilot','Choose one workload, a collector, and the specific metrics or traces to export; configure the provider according to its documentation.','-- Configure the selected provider and OTLP collector outside this demo.'],['Validate end to end','Generate a known query workload, verify signal arrival and labels in the collector, then compare retention and overhead.','SELECT * FROM performance_schema.events_statements_summary_by_digest LIMIT 10;']],
    outcome:'A verified signal path, not just an enabled interface.',
    caution:'The logging interface alone does not export logs. MySQL Enterprise, HeatWave, or a custom logging component is required for logging output.',
    docs:'https://dev.mysql.com/doc/refman/9.7/en/telemetry.html'
  },
  threadpool: {
    release:'MySQL 26.7 Innovation', category:'Concurrency', title:'Thread Pool is now a Community option.',
    lead:'MySQL 26.7 makes the Thread Pool plugin available in Community Edition. Reusable worker groups can reduce scheduling pressure at high connection counts, but only a controlled A/B test can show whether your workload benefits.',
    changes:[['Challenge','One-thread-per-connection can increase thread-stack memory, cache churn, context switching, and InnoDB contention.'],['Mechanism','Thread groups queue statements and assign them to reusable worker threads, keeping active work at sustainable parallelism.'],['Availability','The plugin ships with 26.7 Community but is not active by default; load it explicitly at server startup.'],['26.7 default','thread_pool_max_unused_threads rises from 2 to 32; verify the effective setting after installation.']],
    steps:[
      ['Baseline the default mode','On a disposable 26.7 server, prepare one fixed dataset. Measure the unchanged server at 32, 128, and 512 clients; record TPS, p95/p99, errors, CPU, and active threads.','SELECT VERSION();\nSHOW VARIABLES LIKE \'thread_handling\';\nSHOW GLOBAL STATUS LIKE \'Threads_running\';'],
      ['Check and install the plugin','Confirm thread_pool.so is present in the directory returned by SHOW VARIABLES LIKE \'plugin_dir\'. Back up my.cnf, add the startup option below, then restart mysqld. Use thread_pool.dll on Windows.','[mysqld]\nplugin-load-add=thread_pool.so'],
      ['Verify activation','Expect ACTIVE and thread_handling=loaded-dynamically. MySQL 26.7 Thread Pool monitors live in Performance Schema. Inspect the error log if loading fails.','SELECT PLUGIN_NAME, PLUGIN_STATUS\nFROM information_schema.PLUGINS\nWHERE PLUGIN_NAME = \'thread_pool\';\nSHOW VARIABLES LIKE \'thread_handling\';\nSELECT TABLE_NAME FROM information_schema.TABLES\nWHERE TABLE_SCHEMA = \'performance_schema\' AND TABLE_NAME LIKE \'tp%\';'],
      ['Prepare and repeat the benchmark','Run identical sysbench read/write trials without and with the plugin. Prepare data once, warm up for 30 seconds, run for 180 seconds, repeat each client count three times, and compare medians.','sysbench oltp_read_write --db-driver=mysql \\\n  --mysql-host=HOST --mysql-user=bench --mysql-db=sbtest \\\n  --tables=16 --table-size=100000 prepare\n\nsysbench oltp_read_write --db-driver=mysql \\\n  --mysql-host=HOST --mysql-user=bench --mysql-db=sbtest \\\n  --tables=16 --table-size=100000 --threads=128 \\\n  --warmup-time=30 --time=180 --report-interval=10 run'],
      ['Tune and decide','For InnoDB, start thread_pool_size near physical core count (up to 512); this is a startup-only setting. Retest after tuning and keep the original configuration as the rollback path.','SHOW VARIABLES LIKE \'thread_pool_size\';\nSELECT * FROM performance_schema.tp_thread_group_stats;\n-- To revert: remove plugin-load-add, restart, and verify thread_handling.']
    ],
    outcome:'A side-by-side result at your real concurrency target: TPS, p95/p99, errors, CPU, and active-thread behavior for both modes.',
    caution:'Use a staging instance and a secure test credential. Do not assume the historical Oracle benchmark is a 26.7 result or a universal speedup.',
    docs:'https://dev.mysql.com/doc/refman/26.7/en/thread-pool.html'
  },
  grstack: {
    release:'MySQL 26.7 Innovation', category:'Group Replication', title:'The MYSQL communication stack becomes the default.',
    lead:'New Group Replication configurations in 26.7 default to MYSQL rather than XCOM. Review networking, authentication, TLS, and mixed-version behavior before changing an existing group.',
    changes:[['Default changed','group_replication_communication_stack now defaults to MYSQL.'],['Operational implication','Group communication uses MySQL protocol facilities and their security configuration.'],['Migration posture','Inspect the current setting; do not assume an upgraded group was automatically converted.']],
    steps:[['Inspect every member','Record version, stack, group state, and network/TLS settings on every member.','SHOW VARIABLES LIKE \'group_replication_communication_stack\';\nSELECT * FROM performance_schema.replication_group_members;'],['Plan a lab group','Create a new disposable 26.7 group using the MYSQL stack and validate member joins and recovery.','-- Follow the 26.7 Group Replication configuration procedure.'],['Exercise failure and rollback','Test member restart and primary change; compare with the existing XCOM group before any production migration.','SELECT * FROM performance_schema.replication_group_member_stats;']],
    outcome:'A documented compatibility and failover result, not just a changed default.',
    caution:'Changing communication stack on an existing group is a coordinated topology operation, not a single-node toggle.',
    docs:'https://dev.mysql.com/doc/refman/26.7/en/group-replication-connection-security.html'
  },
  undo: {
    release:'MySQL 26.7 Innovation', category:'InnoDB', title:'Undo truncation progress lives in the tablespace header.',
    lead:'In MySQL 26.7, InnoDB records in-progress undo truncation in the tablespace file header instead of creating new local undo_*_trunc.log marker files. The change simplifies crash recovery state; application rollback and MVCC behavior stay the same.',
    changes:[['Background','Undo logs support rollback and consistent reads; long transactions and heavy writes can grow undo tablespaces.'],['Header state','A selected undo space is marked unusable in its file header while truncation runs; the flag is cleared on completion.'],['Recovery','After interruption, startup reads the header and recovers the affected space. Old marker files remain recognized for backward compatibility.']],
    steps:[
      ['Inventory before upgrade','Back up and test restore. Record the undo-space states, file locations, truncation settings, and long-running transactions before changing binaries.','SELECT VERSION(), @@innodb_undo_log_truncate,\n       @@innodb_max_undo_log_size;\nSELECT NAME, STATE FROM information_schema.INNODB_TABLESPACES\nWHERE NAME LIKE \'%undo%\';\nSELECT TABLESPACE_NAME, FILE_NAME FROM information_schema.FILES\nWHERE FILE_TYPE LIKE \'UNDO LOG\';'],
      ['Upgrade a staging copy','Undo header tracking is built into 26.7 InnoDB: no separate plugin or component is installed. Use the supported upgrade path and inspect startup recovery and the error log.','SELECT VERSION();\nSELECT NAME, STATE FROM information_schema.INNODB_TABLESPACES\nWHERE NAME LIKE \'%undo%\';'],
      ['Trigger manual truncation in a lab','Manual truncation requires three active undo spaces. Create a third space in an isolated test instance, mark it inactive, poll for EMPTY, then reactivate it. Confirm the file location is valid first.','CREATE UNDO TABLESPACE demo_undo ADD DATAFILE \'demo_undo.ibu\';\nALTER UNDO TABLESPACE demo_undo SET INACTIVE;\nSELECT NAME, STATE FROM information_schema.INNODB_TABLESPACES\nWHERE NAME = \'demo_undo\';\n-- After STATE becomes EMPTY:\nALTER UNDO TABLESPACE demo_undo SET ACTIVE;'],
      ['Exercise recovery only on a clone','On a throwaway clone with a verified backup, interrupt an in-progress truncation and restart. Review the error log and confirm affected spaces and application data are usable. Never force a production crash.','SELECT NAME, STATE FROM information_schema.INNODB_TABLESPACES\nWHERE NAME LIKE \'%undo%\';\nSELECT NAME, SUBSYSTEM, COMMENT FROM information_schema.INNODB_METRICS\nWHERE NAME LIKE \'%truncate%\';'],
      ['Benchmark the outcome','Under a fixed write workload, record undo file size, restart-to-service time, TPS, p95 latency, errors, and transaction correctness. Compare like-for-like runs; do not claim a speedup from the header change alone.','SELECT NAME, STATE FROM information_schema.INNODB_TABLESPACES\nWHERE NAME LIKE \'%undo%\';\n-- Capture operating-system file size and server error log too.']
    ],
    outcome:'Verified undo-space lifecycle, recovery correctness, and measured restart and workload behavior after the 26.7 upgrade.',
    caution:'Automatic truncation needs at least two active undo spaces; manual truncation needs three. Never delete undo files or legacy markers by hand.',
    docs:'https://dev.mysql.com/doc/refman/26.7/en/innodb-undo-tablespaces.html'
  },
  pqc: {
    release:'MySQL 26.7 Innovation', category:'TLS security', title:'Prepare TLS for post-quantum key exchange.',
    lead:'With OpenSSL 3.5 or later, MySQL 26.7 can negotiate PQC-capable TLS 1.3 key-exchange groups. Classical fallback remains available unless you explicitly require PQC.',
    changes:[['Scope','Client, admin, asynchronous replication, and Group Replication recovery TLS channels can participate.'],['Default posture','PQC key exchange is preferred when available; enforcement is opt-in.'],['Verification','Inspect the negotiated key-exchange algorithm, not merely the configured preference.']],
    steps:[['Verify prerequisites','Confirm server/client OpenSSL support and a TLS 1.3 connection in a test environment.','SHOW VARIABLES LIKE \'version_ssl_library\';\nSHOW STATUS LIKE \'Ssl_version\';'],['Negotiate before enforcing','Configure compatible TLS key-exchange groups on both ends and reconnect; keep a classical fallback during the pilot.','SHOW STATUS LIKE \'Tls_key_exchange_algorithm\';'],['Test enforcement safely','Only after all clients negotiate PQC, evaluate force_pqc (or the channel-specific equivalent) in a lab.','SHOW VARIABLES LIKE \'force_pqc\';']],
    outcome:'A verified negotiated algorithm and a client compatibility inventory.',
    caution:'Enforcement can reject older clients. PQC handshake signatures are a separate opt-in setting.',
    docs:'https://dev.mysql.com/doc/refman/26.7/en/post-quantum-crytpography-ssl.html'
  },
  upgrade: {
    release:'MySQL 26.7 Innovation', category:'Upgrade operations', title:'Make the upgrade path visible and testable.',
    lead:'The deck calls out upgrade-check progress and operational improvements. For 26.7, treat this as an upgrade-readiness workflow: validate the supported path, run checks, rehearse, and capture completion evidence.',
    changes:[['Versioning','26.7 starts YY.M.P calendar versioning after 9.7.'],['Planning','Use the documented source-to-target upgrade path and tooling for your deployment.'],['Execution','Record precheck findings, duration, recovery, and application smoke tests.']],
    steps:[['Confirm the path','Inventory the source version, plugins/components, replication topology, and backup status.','SELECT VERSION();\nSHOW PLUGINS;'],['Run upgrade checks','Run MySQL Shell upgrade checker against a staging copy using the target version; resolve actionable findings.','// MySQL Shell (JavaScript mode), example:\nutil.checkForServerUpgrade("user@host:3306", {targetVersion:"26.7.0"});'],['Rehearse and validate','Upgrade staging, record check and restart progress, then verify application queries, replication, and rollback plan.','SELECT VERSION();\nSHOW REPLICA STATUS\\G']],
    outcome:'A go/no-go record for a supported 26.7 upgrade path.',
    caution:'The exact MySQL Shell option and supported paths depend on Shell/server versions; confirm against current upgrade documentation before running.',
    docs:'https://dev.mysql.com/doc/mysql-shell/26.7/en/mysql-shell-utilities-upgrade.html'
  }
};

function renderTwentySixDetail(key) {
  if(key==='undo') return `<section class="story-section"><div class="section-label">HOW TRUNCATION WORKS</div><h2>The header carries the in-progress state.</h2><div class="process-line mechanism"><div><span>01 / SELECT</span><strong>Drain a space</strong><small>Stop new rollback-segment assignments.</small></div><b>→</b><div><span>02 / MARK</span><strong>Header flag</strong><small>The file is unusable during truncation.</small></div><b>→</b><div><span>03 / SHRINK</span><strong>Purge + truncate</strong><small>Wait for old undo, then reclaim space.</small></div><b>→</b><div><span>04 / RETURN</span><strong>Clear the flag</strong><small>The space is available again.</small></div></div><p class="takeaway-line">If startup finds an interrupted operation, it recovers the affected undo space from the header state, redo, and DDL logs.</p></section>
    <section class="story-section"><div class="section-label">BEFORE AND AFTER</div><h2>Recovery no longer creates a new local marker file.</h2><div class="comparison-wrap"><table class="comparison-table"><thead><tr><th>Detail</th><th>Earlier releases</th><th>MySQL 26.7</th></tr></thead><tbody><tr><th>Progress marker</th><td>Local undo_*_trunc.log file</td><td>Undo tablespace file header</td></tr><tr><th>Interrupted operation</th><td>Marker guides startup recovery</td><td>Header flag plus redo/DDL logs guide recovery</td></tr><tr><th>Legacy files</th><td>Created during truncation</td><td>Still read at startup; no new files created</td></tr><tr><th>Application behavior</th><td>Rollback and MVCC</td><td>Same rollback and MVCC</td></tr></tbody></table></div></section>
    <section class="story-section"><div class="section-label">BENCHMARK METHOD</div><h2>Separate recovery validation from performance claims.</h2><div class="editorial-list"><div><b>Recovery correctness</b><span>On an isolated clone, record restart-to-service time, error-log outcome, undo-space state, and transaction correctness after interruption.</span></div><div><b>File lifecycle</b><span>Measure file size before and after purge/truncation with the same workload and threshold.</span></div><div><b>Steady-state load</b><span>Compare repeated TPS, p95 latency, and errors under the same write mix. No universal 26.7 speedup is claimed.</span></div></div></section>`;
  if(key==='threadpool') return `<section class="story-section"><div class="section-label">HOW THE POOL HELPS</div><h2>Connections share reusable execution workers.</h2><div class="process-line mechanism"><div><span>01 / CLIENTS</span><strong>Many connect</strong><small>Connections can remain open.</small></div><b>→</b><div><span>02 / GROUPS</span><strong>Queue work</strong><small>Statements are scheduled.</small></div><b>→</b><div><span>03 / WORKERS</span><strong>Reuse threads</strong><small>Limit runnable work.</small></div><b>→</b><div><span>04 / INNODB</span><strong>Execute</strong><small>Sustainable parallelism.</small></div></div><p class="takeaway-line">The pool can limit thread overhead and resource contention at high concurrency; it does not reduce the number of SQL statements.</p></section>
    <section class="story-section"><div class="section-label">PUBLISHED BENCHMARK · NOT A 26.7 RESULT</div><h2>Oracle’s earlier test shows why high concurrency matters.</h2><p class="section-intro">In a published MySQL 8.0.34 TPCC-style run on a 48-core Xeon, the default connection model processed about 2,000 TPS above 4,096 users, versus about 17,000 TPS with Thread Pool. Pool size was 48 with algorithm 1. Different hardware and workloads can change the outcome.</p><div class="benchmark-band"><div><strong>8.0<span>.34</span></strong><small>Oracle’s tested MySQL version</small></div><div><strong>~2k</strong><small>default TPS above 4,096 users</small></div><div><strong>~17k</strong><small>Thread Pool TPS above 4,096 users</small></div></div><p class="caption-note">This historical result illustrates the mechanism. It is not a 26.7 measurement or a universal 8.5× gain. <a href="https://blogs.oracle.com/mysql/the-new-mysql-thread-pool" target="_blank" rel="noopener noreferrer">Oracle benchmark ↗</a></p></section>
    <section class="story-section"><div class="section-label">LOCAL A/B SCORECARD</div><h2>Enter your measured 26.7 results.</h2><div class="measurement-grid"><label>Default · transactions/s<input type="number" min="0" step="0.01" inputmode="decimal" id="tpDefaultTps" placeholder="Measured median"></label><label>Thread Pool · transactions/s<input type="number" min="0" step="0.01" inputmode="decimal" id="tpPoolTps" placeholder="Measured median"></label><label>Default · p95 latency (ms)<input type="number" min="0" step="0.01" inputmode="decimal" id="tpDefaultP95" placeholder="Measured p95"></label><label>Thread Pool · p95 latency (ms)<input type="number" min="0" step="0.01" inputmode="decimal" id="tpPoolP95" placeholder="Measured p95"></label><div class="measurement-result" id="tpResult" aria-live="polite">Enter your measured throughput and p95 values. No result is simulated.</div></div><p class="caption-note">Also compare p99, errors, CPU, Threads_running, and pool monitor data. Use the same 26.7 build, data, workload, and hardware in both modes.</p></section>`;
  return '';
}

function renderFeatureGuide(key) {
  const f=featureGuides[key];
  const rows=f.changes.map(([name,description])=>`<div><b>${name}</b><span>${description}</span></div>`).join('');
  const steps=f.steps.map(([title,description,sql],i)=>`<article class="guide-step"><div class="guide-step-copy"><span class="story-index">0${i+1} / EVALUATE</span><h3>${title}</h3><p>${description}</p></div><div class="code-panel"><div class="code-panel-head"><span>EXAMPLE / READ OR ADAPT</span><span>${key==='threadpool'&&i===1?'MY.CNF':key==='threadpool'&&i===3?'SHELL':'MYSQL'}</span></div><pre><code>${sql}</code></pre></div></article>`).join('');
  const home=key==='ha97'||key==='telemetry'||key==='hypergraph'?'97':'26';
  const detail=renderTwentySixDetail(key);
  const benchmarkStart=detail.indexOf(key==='undo'?'<section class="story-section"><div class="section-label">BENCHMARK METHOD':'<section class="story-section"><div class="section-label">PUBLISHED BENCHMARK');
  const beforeLab=benchmarkStart<0?detail:detail.slice(0,benchmarkStart);
  const afterLab=benchmarkStart<0?'':detail.slice(benchmarkStart);
  return `<div class="page-stack"><section class="editorial-hero compact"><div class="eyebrow">${f.release} · ${f.category}</div><h1>${f.title}</h1><p>${f.lead}</p><div class="hero-actions"><button class="button-red" data-scroll="guide-steps">Follow the evaluation <span aria-hidden="true">↓</span></button>${key==='undo'||key==='threadpool'?'<a class="text-link" href="outputs/mysql-26-7-undo-thread-pool-deep-dive-oracle-style.pptx" download>Download the deep-dive PPT ↗</a>':''}<button class="text-link" data-page-link="${home}">Back to release →</button></div></section><section class="story-section"><div class="section-label">WHAT CHANGED</div><h2>The feature in context.</h2><div class="editorial-list">${rows}</div></section>${beforeLab}<section class="story-section" id="guide-steps"><div class="section-label">DEEP-DIVE TUTORIAL</div><h2>Evaluate it step by step.</h2><p class="section-intro">These are instructional examples, not commands executed by the web app. Use a disposable or staging environment and substitute your own topology and workload.</p><div class="guide-steps">${steps}</div></section>${afterLab}<section class="notice-band"><strong>Expected outcome</strong><span>${f.outcome}</span></section><section class="notice-band subtle"><strong>Before you run</strong><span>${f.caution}</span></section><div class="reference-line"><span>OFFICIAL REFERENCE</span><a href="${f.docs}" target="_blank" rel="noopener noreferrer">MySQL documentation ↗</a>${key==='threadpool'?'<a href="https://dev.mysql.com/doc/refman/26.7/en/thread-pool-installation.html" target="_blank" rel="noopener noreferrer">Installation ↗</a><a href="https://dev.mysql.com/doc/refman/26.7/en/thread-pool-tuning.html" target="_blank" rel="noopener noreferrer">Tuning ↗</a><a href="https://dev.mysql.com/doc/relnotes/mysql/26.7/en/" target="_blank" rel="noopener noreferrer">26.7 release notes ↗</a>':''}</div></div>`;
}
